// Generated by tools/oklch-to-srgb.py from design/stitch-reference.html.
// DO NOT EDIT. Re-run the script if the Stitch palette changes.
//
// All OKLCH tokens were converted via the OKLab -> linear sRGB -> sRGB
// gamma pipeline (Bjorn Ottosson's OKLab matrix). Hex tokens were
// promoted to AARRGGBB with full alpha.
//
// Conversion matrix and formula are stable and reproducible: running
// the generator twice on unchanged input produces a byte-identical
// header (verified in Phase 1 gate).

#pragma once

#include <juce_graphics/juce_graphics.h>

namespace cabrot::theme
{

inline const juce::Colour background { juce::uint32 (0xFF020704) };  // background = oklch(0.12 0.015 160)
inline const juce::Colour border { juce::uint32 (0x991A2E1E) };  // border = oklch(0.28 0.04 150 / 60%)
inline const juce::Colour danger { juce::uint32 (0xFFFF0022) };  // danger = oklch(0.65 0.28 25)
inline const juce::Colour error { juce::uint32 (0xFFFFB4AB) };  // error = #ffb4ab
inline const juce::Colour errorContainer { juce::uint32 (0xFF93000A) };  // error-container = #93000a
inline const juce::Colour foreground { juce::uint32 (0xFFEAF6EA) };  // foreground = oklch(0.96 0.02 145)
inline const juce::Colour inverseOnSurface { juce::uint32 (0xFF293325) };  // inverse-on-surface = #293325
inline const juce::Colour inversePrimary { juce::uint32 (0xFF036E00) };  // inverse-primary = #036e00
inline const juce::Colour inverseSurface { juce::uint32 (0xFFDAE6D1) };  // inverse-surface = #dae6d1
inline const juce::Colour mutedForeground { juce::uint32 (0xFF7E9682) };  // muted-foreground = oklch(0.65 0.04 150)
inline const juce::Colour onBackground { juce::uint32 (0xFFDAE6D1) };  // on-background = #dae6d1
inline const juce::Colour onError { juce::uint32 (0xFF690005) };  // on-error = #690005
inline const juce::Colour onErrorContainer { juce::uint32 (0xFFFFDAD6) };  // on-error-container = #ffdad6
inline const juce::Colour onPrimary { juce::uint32 (0xFF013A00) };  // on-primary = #013a00
inline const juce::Colour onPrimaryContainer { juce::uint32 (0xFF037200) };  // on-primary-container = #037200
inline const juce::Colour onPrimaryFixed { juce::uint32 (0xFF002200) };  // on-primary-fixed = #002200
inline const juce::Colour onPrimaryFixedVariant { juce::uint32 (0xFF025300) };  // on-primary-fixed-variant = #025300
inline const juce::Colour onSecondary { juce::uint32 (0xFF22342A) };  // on-secondary = #22342a
inline const juce::Colour onSecondaryContainer { juce::uint32 (0xFFA5BAAC) };  // on-secondary-container = #a5baac
inline const juce::Colour onSecondaryFixed { juce::uint32 (0xFF0D1F16) };  // on-secondary-fixed = #0d1f16
inline const juce::Colour onSecondaryFixedVariant { juce::uint32 (0xFF384B40) };  // on-secondary-fixed-variant = #384b40
inline const juce::Colour onSurface { juce::uint32 (0xFFDAE6D1) };  // on-surface = #dae6d1
inline const juce::Colour onSurfaceVariant { juce::uint32 (0xFFBACCB1) };  // on-surface-variant = #baccb1
inline const juce::Colour onTertiary { juce::uint32 (0xFF432A21) };  // on-tertiary = #432a21
inline const juce::Colour onTertiaryContainer { juce::uint32 (0xFF7A5A4F) };  // on-tertiary-container = #7a5a4f
inline const juce::Colour onTertiaryFixed { juce::uint32 (0xFF2C160E) };  // on-tertiary-fixed = #2c160e
inline const juce::Colour onTertiaryFixedVariant { juce::uint32 (0xFF5C4036) };  // on-tertiary-fixed-variant = #5c4036
inline const juce::Colour outline { juce::uint32 (0xFF85967D) };  // outline = #85967d
inline const juce::Colour outlineVariant { juce::uint32 (0xFF3C4B36) };  // outline-variant = #3c4b36
inline const juce::Colour primary { juce::uint32 (0xFFF0FFE6) };  // primary = #f0ffe6
inline const juce::Colour primaryContainer { juce::uint32 (0xFF40FF2F) };  // primary-container = #40ff2f
inline const juce::Colour primaryFixed { juce::uint32 (0xFF77FF60) };  // primary-fixed = #77ff60
inline const juce::Colour primaryFixedDim { juce::uint32 (0xFF0FE605) };  // primary-fixed-dim = #0fe605
inline const juce::Colour secondary { juce::uint32 (0xFFB6CCBD) };  // secondary = #b6ccbd
inline const juce::Colour secondaryContainer { juce::uint32 (0xFF384B40) };  // secondary-container = #384b40
inline const juce::Colour secondaryFixed { juce::uint32 (0xFFD2E8D9) };  // secondary-fixed = #d2e8d9
inline const juce::Colour secondaryFixedDim { juce::uint32 (0xFFB6CCBD) };  // secondary-fixed-dim = #b6ccbd
inline const juce::Colour surface { juce::uint32 (0xFF06100A) };  // surface = oklch(0.16 0.02 160)
inline const juce::Colour surfaceBright { juce::uint32 (0xFF323C2D) };  // surface-bright = #323c2d
inline const juce::Colour surfaceContainer { juce::uint32 (0xFF182215) };  // surface-container = #182215
inline const juce::Colour surfaceContainerHigh { juce::uint32 (0xFF232D1F) };  // surface-container-high = #232d1f
inline const juce::Colour surfaceContainerHighest { juce::uint32 (0xFF2D3829) };  // surface-container-highest = #2d3829
inline const juce::Colour surfaceContainerLow { juce::uint32 (0xFF141E11) };  // surface-container-low = #141e11
inline const juce::Colour surfaceContainerLowest { juce::uint32 (0xFF071005) };  // surface-container-lowest = #071005
inline const juce::Colour surfaceDim { juce::uint32 (0xFF0C160A) };  // surface-dim = #0c160a
inline const juce::Colour surfaceElevated { juce::uint32 (0xFF0B1A12) };  // surface-elevated = oklch(0.20 0.025 160)
inline const juce::Colour surfaceTint { juce::uint32 (0xFF0FE605) };  // surface-tint = #0fe605
inline const juce::Colour surfaceVariant { juce::uint32 (0xFF2D3829) };  // surface-variant = #2d3829
inline const juce::Colour tertiary { juce::uint32 (0xFFFFF9F8) };  // tertiary = #fff9f8
inline const juce::Colour tertiaryContainer { juce::uint32 (0xFFFFD5C7) };  // tertiary-container = #ffd5c7
inline const juce::Colour tertiaryFixed { juce::uint32 (0xFFFFDBCF) };  // tertiary-fixed = #ffdbcf
inline const juce::Colour tertiaryFixedDim { juce::uint32 (0xFFE6BEB0) };  // tertiary-fixed-dim = #e6beb0
inline const juce::Colour toxic { juce::uint32 (0xFF40FF2F) };  // toxic = oklch(0.88 0.28 142)
inline const juce::Colour toxicGlow { juce::uint32 (0xFF54FF00) };  // toxic-glow = oklch(0.92 0.30 140)
inline const juce::Colour warning { juce::uint32 (0xFFFFA900) };  // warning = oklch(0.82 0.22 75)

} // namespace cabrot::theme
